### PR TITLE
[#23] Make it build with GHC-8.6.3

### LINKED ISSUE #23: Doesn't build with GHC-8.6.3
When trying to build the project I get the following error:

```
src/Control/Teardown/Internal/Core.hs:171:10: error:
    • Illegal nested constraint ‘(TypeError ...)’
      (Use UndecidableInstances to permit this)
    • In the instance declaration for ‘IResource [(Text, IO ())]’
    |
171 | instance Ty.TypeError ('Ty.Text "DEPRECATED: Execute a 'newTeardown' call per allocated resource")
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #23

### CODE REVIEW

**Comment by roman** [comment]
Thank you!

**Comment by chshersh** [comment]
@roman Thanks for merging! Could you, please, also release these changes to Hackage?

**Comment by roman** [comment]
@ChShersh new version `0.5.0.1` was just released to hackage, apologies for the delay
