### ISSUE TITLE
Doesn't build with GHC-8.6.3

### ISSUE THREAD

**Issue by vrom911** [roman/Haskell-teardown#23]
When trying to build the project I get the following error:

```
src/Control/Teardown/Internal/Core.hs:171:10: error:
    • Illegal nested constraint ‘(TypeError ...)’
      (Use UndecidableInstances to permit this)
    • In the instance declaration for ‘IResource [(Text, IO ())]’
    |
171 | instance Ty.TypeError ('Ty.Text "DEPRECATED: Execute a 'newTeardown' call per allocated resource")
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
